name: example
description: Example app for the JsonDynamicWidget library

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_dynamic_widget:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   json_theme:
#     path: ../../json_theme

flutter:
  uses-material-design: true
  assets:
    - assets/pages/
