name: 'example'
description: 'Example app for the JsonDynamicWidget library'
publish_to: 'none'
version: '1.0.0+26'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  child_builder: '^2.0.0+3'
  desktop_window: '^0.4.0'
  dotted_border: '^2.0.0+3'
  flutter:
    sdk: 'flutter'
  flutter_svg: '^1.1.6'
  json_class: '^2.1.4'
  json_dynamic_widget:
    path: '../'
  json_theme: '^5.0.0'
  logging: '^1.1.0'
  yaon: '^1.0.1+8'

dev_dependencies:
  flutter_test:
    sdk: 'flutter'

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
    - 'assets/pages/'
    - 'assets/secrets/'
    - 'assets/widgets/'
  fonts:
    - family: 'lato'
      fonts:
        - asset: 'assets/fonts/Lato-Regular.ttf'

    - family: 'metal'
      fonts:
        - asset: 'assets/fonts/MetalMania-Regular.ttf'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
