name: json_dynamic_widget
description: A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.
homepage: https://github.com/peiffer-innovations/json_dynamic_widget

version: 1.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"

analyzer:
  exclude: [lib/generated/**]

dependencies:
  flutter:
    sdk: flutter
  child_builder: ^1.0.0+1
  form_validation: ^1.0.0+1
  json_class: ^1.0.6
  json_conditional: ^1.0.3
  json_schema: ^2.2.1
  json_theme: ^1.2.3
  logging: ^0.11.4
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   json_theme:
#     path: ../json_theme

flutter:
  uses-material-design: true
