name: "json_dynamic_widget_codegen"
description: "A library autogenerate JSON widget builders."
homepage: "https://github.com/peiffer-innovations/json_dynamic_widget"
version: "4.1.0"

environment:
  sdk: "^3.9.0"
resolution: "workspace"

analyzer:
  exclude:
    - "lib/generated/**"
    - "lib/**/*.g.dart"

dependencies:
  analyzer: "^8.4.0"
  build: "^4.0.3"
  code_builder: "^4.11.1"
  dynamic_widget_annotation: "^3.0.1"
  json_class: "^3.0.1"
  json_theme: "^11.0.0"
  recase: "^4.1.0"
  source_gen: "^4.1.1"
  template_expressions: "^3.3.1+2"
  yaml_writer: "^2.1.0"
  yaon: "^1.1.4+10"

dev_dependencies:
  flutter_lints: "^6.0.0"
  test: "^1.26.3"

permittedLicenses:
  - "Apache-2.0"
  - "BSD-2-Clause"
  - "BSD-3-Clause"
  - "MIT"
  - "MIT-Modern-Variant"
  - "MPL-2.0"
  - "Zlib"

packageLicenseOverride:
  flutter: "BSD-3-Clause"
  flutter_driver: "BSD-3-Clause"
  flutter_goldens: "BSD-3-Clause"
  flutter_localizations: "BSD-3-Clause"
  flutter_web_plugins: "BSD-3-Clause"
  flutter_test: "BSD-3-Clause"
  fuchsia_remote_debug_protocol: "BSD-3-Clause"
  integration_test: "BSD-3-Clause"
  rxdart: "Apache-2.0"
  sky_engine: "BSD-3-Clause"

ignore_updates:
  - "analyzer"
  - "archive"
  - "async"
  - "boolean_selector"
  - "characters"
  - "charcode"
  - "collection"
  - "clock"
  - "crypto"
  - "fake_async"
  - "file"
  - "matcher"
  - "material_color_utilities"
  - "meta"
  - "path"
  - "source_span"
  - "stack_trace"
  - "stream_channel"
  - "string_scanner"
  - "sync_http"
  - "term_glyph"
  - "test"
  - "test_api"
  - "typed_data"
  - "vector_math"
  - "webdriver"
