name: "json_dynamic_widget_example"
description: "Example app for the JsonDynamicWidget library"
publish_to: "none"
version: "1.0.0+93"

environment:
  sdk: "^3.9.0"

dependencies:
  child_builder: "^2.0.2"
  desktop_window: "^0.4.2"
  dotted_border: "^3.1.0"
  execution_timer: "^1.1.0+13"
  flutter:
    sdk: "flutter"
  flutter_svg: "^2.2.3"
  json_class: "^3.0.1"
  json_dynamic_widget:
    path: "../../packages/json_dynamic_widget"
  json_theme: "^11.0.0"
  logging: "^1.3.0"
  yaon: "^1.1.4+10"

dev_dependencies:
  build_runner: "^2.10.4"
  flutter_lints: "^6.0.0"
  flutter_test:
    sdk: "flutter"
  icons_launcher: "^3.0.3"
  json_dynamic_widget_codegen: "^4.0.1+2"
  yaml_writer: "^2.1.0"

dependency_overrides:
  dynamic_widget_annotation:
    path: "../../packages/annotation"
  json_dynamic_widget_codegen:
    path: "../../packages/codegen"

icons_launcher:
  image_path: "assets-src/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    linux:
      enable: true
    macos:
      enable: true
    web:
      enable: true
    windows:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/pages/"
    - "assets/secrets/"
    - "assets/widgets/"
  fonts:
    - family: "lato"
      fonts:
        - asset: "assets/fonts/Lato-Regular.ttf"
    - family: "metal"
      fonts:
        - asset: "assets/fonts/MetalMania-Regular.ttf"

permittedLicenses:
  - "Apache-2.0"
  - "BSD-2-Clause"
  - "BSD-3-Clause"
  - "MIT"
  - "MIT-Modern-Variant"
  - "MPL-2.0"
  - "Zlib"

packageLicenseOverride:
  flutter: "BSD-3-Clause"
  flutter_driver: "BSD-3-Clause"
  flutter_goldens: "BSD-3-Clause"
  flutter_localizations: "BSD-3-Clause"
  flutter_web_plugins: "BSD-3-Clause"
  flutter_test: "BSD-3-Clause"
  fuchsia_remote_debug_protocol: "BSD-3-Clause"
  integration_test: "BSD-3-Clause"

ignore_updates:
  - "archive"
  - "async"
  - "boolean_selector"
  - "characters"
  - "charcode"
  - "collection"
  - "clock"
  - "crypto"
  - "fake_async"
  - "file"
  - "matcher"
  - "material_color_utilities"
  - "meta"
  - "path"
  - "source_span"
  - "stack_trace"
  - "stream_channel"
  - "string_scanner"
  - "sync_http"
  - "term_glyph"
  - "test_api"
  - "typed_data"
  - "vector_math"
  - "webdriver"
