name: 'json_dynamic_widget'
description: 'A library to dynamically generate widgets within Flutter from JSON or other Map-like structures.'
repository: 'https://github.com/peiffer-innovations/json_dynamic_widget/tree/main/json_dynamic_widget'
version: '7.1.0+8'

environment: 
  sdk: '>=3.0.0 <4.0.0'

analyzer: 
  exclude: 
    - 'lib/generated/**'

dependencies: 
  child_builder: '^2.0.2'
  collection: '^1.17.1'
  dynamic_widget_annotation: '^1.1.2+4'
  execution_timer: '^1.1.0+6'
  flutter: 
    sdk: 'flutter'
  form_validation: '^3.1.1+5'
  interpolation: '^2.1.2'
  json_class: '^3.0.0+13'
  json_conditional: '^3.0.1+10'
  json_schema: '^5.1.7'
  json_theme: '^6.4.1+3'
  logging: '^1.2.0'
  meta: '^1.9.1'
  template_expressions: '^3.2.0+5'
  uuid: '^4.1.0'
  yaml_writer: '^2.0.0'
  yaon: '^1.1.4+8'

dev_dependencies: 
  build_runner: '^2.4.9'
  flutter_lints: '^3.0.2'
  flutter_test: 
    sdk: 'flutter'
  json_dynamic_widget_codegen: '^1.0.5+8'

dependency_overrides: 
  json_dynamic_widget_codegen: 
    path: '../codegen'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'uuid'
  - 'vector_math'
  - 'webdriver'
