name: Flutter Pages Deployer

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/pages.yml
      - json_dynamic_widget/pubspec.yaml

jobs:
  build_number:
    runs-on: ubuntu-latest
    outputs:
      buildnumber: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate Build Number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Build Number
        run: echo "Build Number - $BUILD_NUMBER"

  publish:
    needs: build_number
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run Codegen
        run: |
          flutter packages get
          dart run build_runner build --delete-conflicting-outputs -v
        working-directory: json_dynamic_widget

      - name: Run Codegen (example)
        run: |
          flutter packages get
          dart run build_runner build --delete-conflicting-outputs -v
        working-directory: json_dynamic_widget/example

      - name: Web
        uses: peiffer-innovations/actions-flutter-deploy-pages@v1
        with:
          build_flags: --no-tree-shake-icons
          build_mode: release
          build_number: ${{ needs.build_number.outputs.buildnumber }}
          deploy_path: web
          repo_url: https://github.com/${{ github.repository }}
          source_path: json_dynamic_widget/example
          token: ${{ secrets.GITHUB_TOKEN }}
